[package]
name = "dlib-support"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dlib-sys = {path = "../dlib-sys/"}
railwork = {path = "../railwork/"}
crossbeam-channel = "0.5.15"
