name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Install Nix
        uses: cachix/install-nix-action@master
      - uses: cachix/cachix-action@master
        with:
          name: dines97
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        run: nix develop --command cargo build --verbose
      - name: Run tests
        run: nix develop --command cargo test --verbose
